-- ─────────────────────────────────────────────────────────────────────────────
-- WALIMATUL — Migration 007: Orders
-- Created: 2026-08-17
-- Depends on: Migration 001 (profiles), Migration 003 (templates), Migration 004 (invitations)
-- ─────────────────────────────────────────────────────────────────────────────
-- PURPOSE:
--   Models the manual Touch 'n Go eWallet QR payment lifecycle.
--   Clients do NOT automatically get paid status.
--   Only Admin approval (via postgres/service role / future admin action) produces 'paid'.
--
-- PAYMENT METHOD: tng_ewallet_qr
--   Distinct from 'qr' because WALIMATUL also has an invitation QR code.
--   Use explicit naming: payment QR ≠ invitation QR.
--
-- ORDER SNAPSHOT PRINCIPLE:
--   amount, template_id, validity_months are captured at order creation.
--   Future template price changes do not alter historical order amounts.
--
-- STATUS LIFECYCLE:
--   created               → pending_payment
--   client submits proof  → pending_verification  (via future Server Action)
--   admin approves        → paid                  (admin only)
--   admin rejects         → payment_rejected
--   client cancels draft  → cancelled
--   refund issued         → refunded
--
-- ON APPROVAL (future):
--   orders.payment_status = 'paid'
--   orders.reviewed_at    = now()
--   orders.reviewed_by    = admin user id
--   orders.paid_at        = now()
--   orders.receipt_number = 'WAL-{YYYY}-{seq}'
--   invitations.status    = 'published'
--   invitations.published_at = now()
--   invitations.expires_at   = now() + (orders.validity_months * INTERVAL '1 month')
--
-- FINANCIAL COLUMN PROTECTION:
--   payment_status, reviewed_at, reviewed_by, paid_at, receipt_number,
--   rejection_reason, receipt_email_sent_at are REVOKED from authenticated role.
--   A BEFORE UPDATE trigger provides defence-in-depth.
-- ─────────────────────────────────────────────────────────────────────────────

-- ── 1. Orders table ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.orders (
  id                      UUID          PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Receipt number (null until approved, generated by Admin action)
  -- Future format: WAL-2026-000001
  receipt_number          TEXT          UNIQUE,

  -- Ownership (RESTRICT: financial records must not vanish if user is deleted)
  user_id                 UUID          NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,

  -- Linked invitation (RESTRICT: preserves financial history)
  invitation_id           UUID          NOT NULL REFERENCES public.invitations(id) ON DELETE RESTRICT,

  -- Template snapshot (immutable after creation)
  template_id             UUID          NOT NULL REFERENCES public.templates(id) ON DELETE RESTRICT,

  -- Financial snapshot (must not change after creation)
  amount                  NUMERIC(10,2) NOT NULL CHECK (amount >= 0),
  currency                TEXT          NOT NULL DEFAULT 'MYR',

  -- Payment method identifier
  -- 'tng_ewallet_qr' = Touch 'n Go eWallet QR (manual verification)
  -- Named explicitly to avoid confusion with the invitation QR code
  payment_method          TEXT          NOT NULL DEFAULT 'tng_ewallet_qr'
                                        CHECK (payment_method IN ('tng_ewallet_qr')),

  -- Client-provided reference (e.g. TNG transaction ID / screenshot reference)
  -- Set when client submits payment proof, not at order creation
  payment_reference       TEXT,

  -- ── Admin-controlled status fields ────────────────────────────────────────
  -- These columns are REVOKED from the authenticated role (see below).
  -- Only postgres/service role or future Admin server actions may modify them.

  -- Payment lifecycle status
  payment_status          TEXT          NOT NULL DEFAULT 'pending_payment'
                                        CHECK (payment_status IN (
                                          'pending_payment',
                                          'pending_verification',
                                          'paid',
                                          'payment_rejected',
                                          'cancelled',
                                          'refunded'
                                        )),

  -- Validity snapshot from template at time of order creation
  validity_months         INTEGER       NOT NULL CHECK (validity_months > 0),

  -- Timestamps
  submitted_at            TIMESTAMPTZ,   -- when client submits payment proof
  reviewed_at             TIMESTAMPTZ,   -- when admin reviews
  reviewed_by             UUID          REFERENCES auth.users(id) ON DELETE SET NULL,
  paid_at                 TIMESTAMPTZ,   -- when admin approves

  -- Rejection
  rejection_reason        TEXT,

  -- Receipt email
  receipt_email_sent_at   TIMESTAMPTZ,

  created_at              TIMESTAMPTZ   NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE TRIGGER on_orders_updated
  BEFORE UPDATE ON public.orders
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_updated_at();

-- ── 2. Indexes ────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_orders_user_id        ON public.orders (user_id);
CREATE INDEX IF NOT EXISTS idx_orders_invitation_id  ON public.orders (invitation_id);
CREATE INDEX IF NOT EXISTS idx_orders_payment_status ON public.orders (payment_status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at     ON public.orders (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_reviewed_by    ON public.orders (reviewed_by);

-- ── 3. Enable RLS ─────────────────────────────────────────────────────────────
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- ── 4. RLS Policies ───────────────────────────────────────────────────────────

-- SELECT: authenticated client can read own orders.
CREATE POLICY "orders: authenticated users read own"
  ON public.orders
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

-- INSERT: client can create orders for themselves.
-- CHECK prevents forging user_id or initial status.
-- Administrative fields (payment_status, reviewed_by, etc.) default values are safe.
CREATE POLICY "orders: authenticated users insert own"
  ON public.orders
  FOR INSERT
  TO authenticated
  WITH CHECK (
    auth.uid() = user_id
    AND payment_status = 'pending_payment'
    AND reviewed_by IS NULL
    AND paid_at IS NULL
    AND receipt_number IS NULL
  );

-- UPDATE: clients can only update limited fields (payment_reference, submitted_at).
-- Administrative fields are protected by column-level REVOKE + trigger (below).
CREATE POLICY "orders: authenticated users update own pending"
  ON public.orders
  FOR UPDATE
  TO authenticated
  USING (
    auth.uid() = user_id
    AND payment_status IN ('pending_payment', 'pending_verification')
  )
  WITH CHECK (auth.uid() = user_id);

-- ── 5. Financial Column Protection (Layer 1: Column-level REVOKE) ─────────────
-- These columns cannot be touched by the 'authenticated' role at the DB level.
-- This enforces at PostgreSQL privilege level — before RLS is evaluated.
REVOKE UPDATE (
  payment_status,
  reviewed_at,
  reviewed_by,
  paid_at,
  receipt_number,
  rejection_reason,
  receipt_email_sent_at
) ON public.orders FROM authenticated;

-- ── 6. Financial Column Protection (Layer 2: BEFORE UPDATE Trigger) ───────────
-- Defence-in-depth: raises exception if authenticated session tries to change admin fields.
CREATE OR REPLACE FUNCTION public.protect_order_admin_fields()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
BEGIN
  IF current_role = 'authenticated' THEN
    IF NEW.payment_status   IS DISTINCT FROM OLD.payment_status   THEN
      RAISE EXCEPTION 'Unauthorized: payment_status cannot be modified directly.';
    END IF;
    IF NEW.reviewed_at      IS DISTINCT FROM OLD.reviewed_at      THEN
      RAISE EXCEPTION 'Unauthorized: reviewed_at cannot be modified directly.';
    END IF;
    IF NEW.reviewed_by      IS DISTINCT FROM OLD.reviewed_by      THEN
      RAISE EXCEPTION 'Unauthorized: reviewed_by cannot be modified directly.';
    END IF;
    IF NEW.paid_at          IS DISTINCT FROM OLD.paid_at          THEN
      RAISE EXCEPTION 'Unauthorized: paid_at cannot be modified directly.';
    END IF;
    IF NEW.receipt_number   IS DISTINCT FROM OLD.receipt_number   THEN
      RAISE EXCEPTION 'Unauthorized: receipt_number cannot be modified directly.';
    END IF;
    IF NEW.rejection_reason IS DISTINCT FROM OLD.rejection_reason THEN
      RAISE EXCEPTION 'Unauthorized: rejection_reason cannot be modified directly.';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_orders_protect_admin_fields
  BEFORE UPDATE ON public.orders
  FOR EACH ROW
  EXECUTE FUNCTION public.protect_order_admin_fields();

-- ─────────────────────────────────────────────────────────────────────────────
-- AUDIT TRAIL NOTE:
--   reviewed_by captures which admin approved/rejected a payment.
--   This field must never be cleared for paid/payment_rejected orders.
--   ON DELETE SET NULL applies only if the admin user account is deleted,
--   which should be a very rare event.
--   The reviewed_at timestamp always preserves the moment of decision.
--
-- PAID ORDERS MUST NOT BE DELETED:
--   ON DELETE RESTRICT on user_id and invitation_id prevents casual deletion
--   of financial records. Deletion of paid orders should require postgres-level
--   intervention and is expected to be an exceptional event.
--
-- PAYMENT QR vs INVITATION QR:
--   This payment uses 'tng_ewallet_qr' for the Touch 'n Go payment QR shown
--   during checkout. This is entirely different from the invitation QR that is
--   generated after payment approval and links to walimatul.my/{slug}.
-- ─────────────────────────────────────────────────────────────────────────────
